upstream hris_app {
    server web:8000;
}

upstream mail_app {
    server mail:8001;
}

# Redirect HTTP ke HTTPS
server {
    listen 80;
    server_name ikira-demo.web.id www.ikira-demo.web.id mail.ikira-demo.web.id;
    return 301 https://$host$request_uri;
}

# HRIS
server {
    listen 443 ssl;
    server_name ikira-demo.web.id www.ikira-demo.web.id;

    ssl_certificate /etc/letsencrypt/live/ikira-demo.web.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ikira-demo.web.id/privkey.pem;

    client_max_body_size 20M;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /app/media/;
        expires 7d;
    }

    location / {
        proxy_pass http://hris_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}

# Mail
server {
    listen 443 ssl;
    server_name mail.ikira-demo.web.id;

    ssl_certificate /etc/letsencrypt/live/mail.ikira-demo.web.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mail.ikira-demo.web.id/privkey.pem;

    client_max_body_size 20M;

    location /static/ {
        alias /app/mail_staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /app/mail_media/;
        expires 7d;
    }

    location / {
        proxy_pass http://mail_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
