# Generated by Django 4.2.9 on 2026-03-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='email',
            new_name='mail_email_recipie_b02a23_idx',
            old_name='mail_email_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='email',
            new_name='mail_email_sender__7b4036_idx',
            old_name='mail_email_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='email',
            new_name='mail_email_thread__8d42f1_idx',
            old_name='mail_email_thread_idx',
        ),
    ]
